# set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"
set -g renumber-windows on
setw -g mode-keys vi
bind r source-file ~/.tmux.conf \; display "reloaded"
set -g @plugin 'catppuccin/tmux#v2.3.0'

# Nvim Navigator
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-open'

# Yank settings
set -g @yank_selection_mouse 'primary'

# Resurrect settings
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# Continuum settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Change the regular expression used to detect vim. This pattern must be
# compatible with `grep -iE` extended regular expression syntax.
set -g @vim_navigator_pattern '(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'

# Override the shell script logic for detecting vim. Instances of
# '@vim_navigator_pattern' will automatically be substituted with your override
# of '@vim_navigator_pattern', or it will use the default @vim_navigator_pattern
# if you haven't overridden the option.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +@vim_navigator_pattern$'"
set -g @vim_navigator_check "${is_vim}"

# change the prefix from 'C-b' to 'C-a'
# (remap capslock to CTRL for easy access)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# start with window 1 (instead of 0)
set -g base-index 1

# start with pane 1
set -g pane-base-index 1

# split panes using | and -, make sure they open in the same path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# new windows inherit cwd
bind c new-window -c "#{pane_current_path}"

# repeatable pane resize (works for repeat-time after prefix)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# quick toggle to last window
bind C-a last-window

# vim/nvim responsiveness + repeatable command window
set -sg escape-time 1
set -g repeat-time 1000

unbind '"'
unbind %

# mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# set default terminal mode to 256 colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# allow focus events to get through to applications running in tmux
set -g focus-events on

# Initialize TMUX plugin manager (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
